version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y yum-utils unzip python3 python3-pip
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      
  pre_build:
    commands:
      - cd terraform
      - aws ssm get-parameter --name "/terraform/vars" --with-decryption --query "Parameter.Value" --output text > terraform.tfvars
      - terraform init
      
  build:
    commands:
      - terraform plan -var-file="terraform.tfvars"
      - terraform apply -var-file="terraform.tfvars" -auto-approve
      
  post_build:
    commands:
      - rm terraform.tfvars
      - echo "Terraform apply completed on `date`"

artifacts:
  files:
    - terraform/tfplan
    - terraform/*.tf
  discard-paths: no 