version: 0.2

env:
  variables:
    ENVIRONMENT: "prod"
    TF_WORKSPACE: "prod"
    TF_VAR_environment: "prod"

phases:
  install:
    commands:
      - yum update -y
      - yum install -y yum-utils unzip python3 python3-pip jq
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - pip3 install checkov
      
  pre_build:
    commands:
      - cd terraform
      - aws ssm get-parameter --name "/terraform/vars/${ENVIRONMENT}" --with-decryption --query "Parameter.Value" --output text | jq -r 'to_entries | .[] | "\(.key) = \(.value)"' > terraform.tfvars
      - terraform init -input=false
      - terraform workspace select ${TF_WORKSPACE} || terraform workspace new ${TF_WORKSPACE}
      
  build:
    commands:
      - echo "Validando configuração do Terraform..."
      - terraform validate
      - echo "Verificando segurança da infraestrutura..."
      - checkov -d .
      - echo "Planejando mudanças..."
      - terraform plan -var-file="terraform.tfvars" -out=tfplan
      - echo "Aguardando aprovação manual..."
      - echo "Para aplicar as mudanças, acesse o console do CodeBuild e aprove a etapa manual."
      
  post_build:
    commands:
      - rm terraform.tfvars
      - echo "Terraform plan completed on `date`"
      - echo "Estado do Terraform salvo no workspace ${TF_WORKSPACE}"

artifacts:
  files:
    - terraform/tfplan
    - terraform/*.tf
  discard-paths: no

cache:
  paths:
    - /root/.terraform.d/plugin-cache/**/* 