version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y yum-utils unzip
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      
  pre_build:
    commands:
      - cd terraform
      - terraform init
      
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
      
  post_build:
    commands:
      - echo "Terraform apply completed on `date`"

artifacts:
  files:
    - terraform/tfplan
    - terraform/*.tf
  discard-paths: no 