AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pipeline de CI/CD para infraestrutura Terraform'

Parameters:
  RepositoryName:
    Type: String
    Description: Nome do repositório GitHub
  GitHubToken:
    Type: String
    Description: Token de acesso do GitHub
    NoEcho: true
  ArtifactBucket:
    Type: String
    Description: Nome do bucket S3 para artefatos

Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: terraform-prod-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Value: prod
          - Name: TF_WORKSPACE
            Value: prod
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: terraform-infrastructure-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Sub '${GitHubOwner}'
                Repo: !Ref RepositoryName
                Branch: main
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1

  ApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Terraform Pipeline Approvals

version: 0.2

stages:
  - name: Source
    actions:
      - name: Source
        actionTypeId:
          category: Source
          owner: AWS
          provider: CodeCommit
          version: 1
        configuration:
          RepositoryName: !Ref RepositoryName
          BranchName: main
        outputArtifacts:
          - name: SourceArtifact
        runOrder: 1

  - name: Build
    actions:
      - name: Build
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: 1
        configuration:
          ProjectName: !Ref BuildProject
        inputArtifacts:
          - name: SourceArtifact
        outputArtifacts:
          - name: BuildArtifact
        runOrder: 1

  - name: Deploy
    actions:
      - name: Deploy
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: 1
        configuration:
          ProjectName: !Ref BuildProject
        inputArtifacts:
          - name: BuildArtifact
        runOrder: 1

artifacts:
  - name: SourceArtifact
  - name: BuildArtifact 