version: 0.2

env:
  variables:
    ENVIRONMENT: "prod"
    TF_WORKSPACE: "prod"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y unzip python3 python3-pip jq
      - curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/
      - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - pip3 install checkov

  pre_build:
    commands:
      - echo "Retrieving SSM parameters..."
      - cd terraform/environments/prod
      - aws ssm get-parameter --name "/terraform/vars" --with-decryption --query "Parameter.Value" --output text > terraform.tfvars
      - terraform init

  build:
    commands:
      - echo "Running Terraform plan and apply..."
      - terraform validate
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Cleaning up..."
      - rm -f terraform.tfvars tfplan

artifacts:
  files:
    - '**/*'
  name: terraform-${ENVIRONMENT}-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - /root/.terraform.d/**/* 