version: 0.2

env:
  variables:
    ENVIRONMENT: "prod"
    TF_WORKSPACE: "prod"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y unzip python3 python3-pip jq
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install -y terraform
      - pip3 install checkov

  pre_build:
    commands:
      - cd terraform/environments/prod
      - aws ssm get-parameter --name "/terraform/vars" --with-decryption --query "Parameter.Value" --output text > terraform.tfvars
      - terraform init -input=false
      - terraform workspace select prod || terraform workspace new prod

  build:
    commands:
      - terraform validate
      - checkov -d .
      - terraform plan -out=tfplan
      - |
        if [ "$ENVIRONMENT" = "prod" ]; then
          echo "Waiting for manual approval for production..."
        else
          terraform apply -auto-approve tfplan
        fi

  post_build:
    commands:
      - rm -f tfplan terraform.tfvars

artifacts:
  files:
    - '**/*'
  name: terraform-${ENVIRONMENT}-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '/root/.terraform.d/**/*' 